version: "3.9"

services:
 db:
   image: postgres
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - db.env
   container_name: db-container

 web:
   build: ./web
   volumes:
     - static_volume:/app/staticfiles
   environment:
     - PORT=8000
   env_file:
     - db.env
   expose:
     - 8000
   depends_on:
     - db
   container_name: web-container

 nginx:
   build: ./nginx
   volumes:
     - static_volume:/app/staticfiles
     - ./data/certbot/conf:/etc/letsencrypt
     - ./data/certbot/www:/var/www/certbot
     - ./ro-data:/app/ro-data
   ports:
     - 80:80
     - 443:443
   depends_on:
     - web
   container_name: nginx-container
   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

 certbot:
   image: certbot/certbot
   volumes:
     - ./data/certbot/conf:/etc/letsencrypt
     - ./data/certbot/www:/var/www/certbot
   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
 postgres_data:
 static_volume:
