version: "3.9"

services:
 db:
   image: postgres
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - db.env
   container_name: db-container

 redis:
   image: "redis:alpine"

 web:
   build: ./web
   volumes:
     - static_volume:/app/staticfiles
   environment:
     - PORT=8000
     - DB_HOST=db
     - TRANSPORT_HOST=redis
     - DEBUG=0
   env_file:
     - db.env
   expose:
     - 8000
   depends_on:
     - db
     - nginx
     - redis
   container_name: web-container

 celery:
   build:
     context: ./web
     dockerfile: Dockerfile-celery
   command: celery -A rnp_find worker -l INFO
   env_file:
     - db.env
   environment:
     - DB_HOST=db
     - TRANSPORT_HOST=redis
     - HOST_URL=https://rnpfind.com
   volumes:
     - static_volume:/app/staticfiles
     - ./ro-data:/usr/local/lib/python3.8/site-packages/rnpfind/ro-data
   depends_on:
     - db
     - redis


 nginx:
   build: ./nginx
   volumes:
     - static_volume:/app/staticfiles
     - ./data/certbot/conf:/etc/letsencrypt
     - ./data/certbot/www:/var/www/certbot
     - ./ro-data:/app/ro-data
   ports:
     - 80:80
     - 443:443
   environment:
     - UPSTREAM_HOST=web
   container_name: nginx-container
   entrypoint: /nginx-entry.sh
   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

 certbot:
   image: certbot/certbot
   volumes:
     - ./data/certbot/conf:/etc/letsencrypt
     - ./data/certbot/www:/var/www/certbot
   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
 postgres_data:
 static_volume:
