version: "3.9"

services:
 db:
   image: postgres
   # volumes:
     # - ./data/db:/var/lib/postgresql/data # dev
   env_file:
     - db.env
   container_name: db-container

 web:
   build: .
   environment:
     - PORT=8000
   env_file:
     - db.env
   volumes:
     - ./ro-data/postar-data:/app/ro-data/postar-data
     - ./ro-data/hg38-human-genome:/app/ro-data/hg38-human-genome
   ports:
     - "8000:8000"
   depends_on:
     - db
   container_name: web-container
