version: "3.9"

services:
 db:
   image: postgres
   # volumes:
     # - ./data/db:/var/lib/postgresql/data # dev
   env_file:
     - db.env
   container_name: db-container

 web:
   build: ./web
   environment:
     - PORT=8000
   env_file:
     - db.env
   expose:
     - 8000
   depends_on:
     - db
   container_name: web-container

 nginx:
   build: ./nginx
   ports:
     - 1337:80
   depends_on:
     - web
   container_name: nginx-container
