version: "3.9"

services:
 db-dev:
   image: postgres
   volumes:
     - postgres_data_dev:/var/lib/postgresql/data
   env_file:
     - db.env
   container_name: db-container-dev

 redis-dev:
   image: "redis:alpine"

 web-dev:
   build: ./web
   volumes:
     - static_volume_dev:/app/staticfiles
     - ./web:/app
   environment:
     - PORT=8000
     - DB_HOST=db-dev
     - TRANSPORT_HOST=redis-dev
   env_file:
     - db.env
   expose:
     - 8000
   depends_on:
     - db-dev
     - nginx-dev
     - redis-dev
   container_name: web-container-dev

 celery-dev:
   build:
     context: ./web
     dockerfile: Dockerfile-celery
   command: celery -A rnp_find worker -l INFO
   env_file:
     - db.env
   environment:
     - DB_HOST=db-dev
     - TRANSPORT_HOST=redis-dev
     - HOST_URL=https://rnpfind.com:4430
   volumes:
     - static_volume_dev:/app/staticfiles
   depends_on:
     - db-dev
     - redis-dev


 nginx-dev:
   build: ./nginx
   volumes:
     - static_volume_dev:/app/staticfiles
     - ./data/certbot/conf:/etc/letsencrypt
     - ./data/certbot/www:/var/www/certbot
     - ./ro-data:/app/ro-data
   ports:
     - 800:80
     - 4430:443
   environment:
     - UPSTREAM_HOST=web-dev
   container_name: nginx-container-dev
   entrypoint: /nginx-entry.sh
   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

 certbot-dev:
   image: certbot/certbot
   volumes:
     - ./data/certbot/conf:/etc/letsencrypt
     - ./data/certbot/www:/var/www/certbot
   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
 postgres_data_dev:
 static_volume_dev:
