# Generated by Django 3.1.1 on 2020-10-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='chromosome_number',
            field=models.CharField(default='chr2', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='end_coord',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='start_coord',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
