# Generated by Django 3.1.1 on 2020-10-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201011_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='ucsc_url',
            field=models.URLField(default='https://www.google.com'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BindingSummaryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source_type', models.CharField(choices=[('RB', 'RBPDB'), ('AT', 'ATTRACT'), ('PO', 'POSTAR')], max_length=2)),
                ('number_of_sites', models.IntegerField()),
                ('number_of_rbps', models.IntegerField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding_summaries', to='website.gene')),
            ],
        ),
    ]
