# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: cli-pytest

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Create directories
      run: mkdir -p ./cli/src/rnpfind/ro-data/hg38-human-genome/
    # - name: Install tools
    #   run: sudo apt install wget && sudo apt install gzip
    - name: Download chromosome 4
      working-directory: ./cli/src/rnpfind/ro-data/hg38-human-genome/
      run: wget https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr4.fa.gz && gzip -d chr4.fa.gz
    - name: Download chromosome 11
      working-directory: ./cli/src/rnpfind/ro-data/hg38-human-genome/
      run: wget https://hgdownload.soe.ucsc.edu/goldenPath/hg38/chromosomes/chr11.fa.gz && gzip -d chr11.fa.gz
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: ./cli
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      working-directory: ./cli
      run: |
        pytest
