FROM python:3.8-slim
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBUG 0

# used by bedToBigBed tool
RUN apt-get update && apt-get install --no-install-recommends -y \
    libkrb5-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY . .

RUN adduser --disabled-password myuser; \
    mkdir /app/staticfiles; \
    chown myuser /app; \
    chown myuser /app/staticfiles; \
    chown myuser /usr/local/lib/python3.8/site-packages/rnpfind; \
    chown myuser /usr/local/lib/python3.8/site-packages/hgfind

USER myuser
CMD ["celery", "-A", "rnp_find", "worker", "-l", "INFO"]

# vi: ft=dockerfile
